### ISSUE TITLE
Add Support for MongoDB 6.x

### ISSUE THREAD

**Issue by GuyPaddock** [lando/mongo#18]
Bitnami now provides MongoDB 6.0 images (e.g., [6.0.9-debian-11-r5](https://hub.docker.com/layers/bitnami/mongodb/6.0.9-debian-11-r5/images/sha256-11d77ada23ab4b468a769763156a42cdab8da88ab2404f2f6c65b40aac13088e?context=explore) and [6.0](https://hub.docker.com/layers/bitnami/mongodb/6.0/images/sha256-11d77ada23ab4b468a769763156a42cdab8da88ab2404f2f6c65b40aac13088e?context=explore)). I'd like to give these a spin in Lando, but I don't know of a good way to override `builder.js` to expose these versions to the recipe.

**Comment by reynoldsalec** [comment]
...working on this now. Bummer is that apparently Bitnami has AVX-reliant features in their images after MongoDB 4.x, and neither QEMU or Rosetta emulation seems to work on an ARM Mac computer :(

Going to be very happy to get into Lando 4 API services and use the core Docker images.

**Comment by reynoldsalec** [comment]
Ok, added 6.x and 7.x in v0.9.0 of this plugin: https://github.com/lando/mongo/releases/tag/v0.9.0

That should get "deployed" with the next Lando release. That release will also include commands for updating Lando plugins ad hoc, so in the future when a fix like this is deployed to a plugin, you can update that plugin without having to wait for a new Lando version or doing a custom install yourself.
